service: "tdean-serverless-websockets-example"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: test
  timeout: 15
  memorySize: 256
  profile: sandbox

functions:
  connect:
    handler: functions/connect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: functions/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  sendMessage:
    handler: functions/sendMessage.handler
    environment:
      WEBSOCKETS_API_DOMAIN:
        Fn::Join:
          - ''
          - - Ref: WebsocketsApi
            - .execute-api.
            - ${self:provider.region}
            - .amazonaws.com/
            - ${self:provider.stage}
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:eu-west-1:255469446966:table/ConnectionsTable/stream/2023-07-12T14:51:56.605
  # We could batch here!

resources:
  Resources:
    connectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: products
            AttributeType: SS    
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1