service: "tdean-serverless-websockets-example"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: test
  timeout: 15
  memorySize: 256
  profile: sandbox
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-west-1:255469446966:table/${self:service}-ConnectionsTable

functions:
  connect:
    handler: functions/connect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: functions/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  sendMessage:
    handler: functions/sendMessage.handler
    environment:
      WEBSOCKETS_API_DOMAIN:
        Fn::Join:
          - ''
          - - Ref: WebsocketsApi
            - .execute-api.
            - ${self:provider.region}
            - .amazonaws.com/
            - ${self:provider.stage}
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:eu-west-1:255469446966:table/tdean-serverless-websockets-example-ConnectionsTable/stream/2023-07-26T09:17:15.543

resources:
  Resources:
  #I would recommend creating this table manually, followed by the stream above ^^^
    connectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-ConnectionsTable
        AttributeDefinitions:
          - AttributeName: requestId
            AttributeType: S 
        KeySchema:
          - AttributeName: requestId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1